### ISSUE TITLE
error in genfromtxt

### ISSUE THREAD

**Issue by SteffenMauceri** [hong-chen/er3t#3]
Hi Hong,

L 541 in util.py throws an error for me when I try to run your 02_modis_rad-sim.py example:

data  = np.genfromtxt(StringIO(content), delimiter=',', skip_header=2, names=True, dtype=dtype, invalid_raise=False, loose=True, usecols=usecols)

...
    Line #1028 (got 1 columns instead of 10)
    Line #1029 (got 1 columns instead of 10)
    Line #1030 (got 1 columns instead of 10)
    Line #1031 (got 1 columns instead of 10)
    Line #1032 (got 1 columns instead of 10)
    Line #1034 (got 1 columns instead of 10)
    Line #1035 (got 1 columns instead of 10)
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<string>", line 1, in <module>
  File "/Users/smauceri/opt/anaconda3/envs/er3t/lib/python3.9/site-packages/numpy/lib/npyio.py", line 2392, in genfromtxt
    dtype.names = names
ValueError: must replace all names at once with a sequence of length 10

Any idea what is happening here?

I am on Mac OSX, Python 3.9 with numpy 1.24.2

In case it helps. Here is the beginning of content: 
"<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Level-1 and Atmosphere Archive &amp; Distribution System Distributed Active Archive Center - LAADS DAAC</title>
    <meta name="WHEREAMI" content="ui-laads"/>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="orgcode" content="619"/>
    <meta name="rno" content="Robert Wolfe"/>
    <meta name="content-owner" content="Greg Ederer"/>
    <meta name="webmaster" content="Greg Ederer"/>
    <meta name="description" content="Level-1 and Atmosphere Archive and Distribution System Web Interface"/>
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <meta name="apple-mobile-web-app-status-bar-style" content="black"/>

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WNP7MLF');</script>

..."

**Comment by hong-chen** [comment]
Hi Steffen,

Thanks for reporting the bug.

This is a knowing issue caused by the unstableness of either the Python `requests` package or the MODIS data archive website when accessing the geo-data text file.

I assume you are using the `master` branch and we (Vikas Nataraja) attempted a fix in the `dev` branch. Could you give it a try at `dev` branch?

Best Regards
Hong Chen

**Comment by vikasnataraja** [comment]
@SteffenMauceri This is a problem caused by the LAADS DAAC servers. We encountered the same issue and have employed a temporary fix here if you want to try it out: https://github.com/hong-chen/er3t/blob/dev/er3t/util/util.py#L670. This fix essentially downloads the metadata file onto your local disk and then reads from there instead of reading it directly on the server which is causing the issue. Lines 670 to 700 specifically are the fix.

**Comment by SteffenMauceri** [comment]
Thanks for the quick help. I will try the fix on dev and report back.

**Comment by SteffenMauceri** [comment]
That resolved the issue. Thanks.

**Comment by hong-chen** [comment]
Please note that currently I am actively modifying the example code (for the final review of the paper) - this will require you to regularly perform `git pull` if you decide to stay in `dev` branch. I will merge all the progress into `master` branch once all the modifications are completed and tested (around mid-March).

**Comment by SteffenMauceri** [comment]
Sounds good Hong,

In that case I will hold off using the code until you are finished developing. 

(I hope to evaluate in how far we can use your tool to develop and operationalize a product for for an upcoming mission called AOS)

Please shoot me a message once you are done. Also happy to be the Guiana pick to see what breaks :)

Best
Steffen

**Comment by hong-chen** [comment]
That's exactly what we planned to do in the future! Sebastian and I have already discussed some exciting ideas around AOS. I would strongly recommend you to join our Discord channel to get the latest news of EaR3T and get involved in some discussions.
